# En config_PPO.yaml
hydra:
  run:
    dir: outputs/SKRL/${env.env_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    

# task and env
env:
  algorithm: PPO
  num_cpu: 8
  use_delayed_sensors: True
  env_name: sconewalk_h0918_osim-v1  #"nair_walk_h1622_exo_hip-v0"   
                                        #"nair_walk_h0918_exo_knee-v1"
                                        #"ExoLegSpasticityFlexoExtEnv-v0"
  path: /home/achs/Documents/AChS/PHD/code/NAIR_Code/envs/sconegym/sconegym/nair_gaitgym.py
  torch_dir: null
# collector
collector:
  buffer_size: 5_000_000
  num_steps: 100_000
  

# logger
logger:
  #backend: wandb
  exp_name: nair_walk_h0918_exo_knee_Espasticity_SAC
  write_interval: 500
  test_interval: 5_000
  check_interval: 100
  num_test_episodes: 5

# Optim
optim:
  lr: 1e-3
  optimizer: KLAdaptiveRL
  optimizer_kwargs: {"kl_threshold": 0.008}
  weight_decay: 0.0
  anneal_lr: True

# loss
hiperparameters:
  discount_factor: 0.9
  lambda_factor: 0.95
  clip_norm: 0.5
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: False
  entropy_loss: 0
  value_loss: 0.5
  kl_threshold: 0
  batch_size: 1024
  mini_batches: 32
  learning_epochs: 10
  train_freq: 1
  gradient_steps: -1
