# task and env
env:
  env_name: ExoLeg40MuscFlexoExtEnv-v0

# collector
collector:
  frames_per_batch: 512
  total_frames: 100_000

# logger
logger:
  backend: wandb
  exp_name: MyoExoLegV0
  test_interval: 10_000
  num_test_episodes: 5

# Optim
optim:
  lr: 5e-4
  weight_decay: 0.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 32
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.5
  anneal_clip_epsilon: False
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2
