# En config_PPO.yaml
hydra:
  run:
    dir: outputs/${env.experiment}/${env.algorithm}/${env.env_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    

# task and env
env:
  experiment: GAIL
  algorithm: PPO
  num_cpu: 1
  use_delayed_sensors: True
  env_name:  nair_walk_h0918-v1 
                                        #nair_walk_h0918_KneeExo_GH_v0   
                                        #nair_walk_h0918KneeExoRS2-v0
                                        #"ExoLegSpasticityFlexoExtEnv-v0"
  torch_dir: null
  input_cols:
    - pelvis_tilt
    - pelvis_tx
    - pelvis_ty
    - hip_flexion_r
    - knee_angle_r
    - ankle_angle_r
    - hip_flexion_l
    - knee_angle_l
    - ankle_angle_l
    - upperexo_hinge
    - upperexo_slide
    - exo_rotation
    - lowerexo_hinge
    - pelvis_tilt_u
    - pelvis_tx_u
    - pelvis_ty_u
    - hip_flexion_r_u
    - knee_angle_r_u
    - ankle_angle_r_u
    - hip_flexion_l_u
    - knee_angle_l_u
    - ankle_angle_l_u
    - upperexo_hinge_u
    - upperexo_slide_u
    - exo_rotation_u
    - lowerexo_hinge_u

  target_cols:
    - hamstrings_r.activation
    - bifemsh_r.activation
    - glut_max_r.activation
    - iliopsoas_r.activation
    - rect_fem_r.activation
    - vas_int_r.activation
    - gastroc_r.activation
    - soleus_r.activation
    - tib_ant_r.activation
    - hamstrings_l.activation
    - bifemsh_l.activation
    - glut_max_l.activation
    - iliopsoas_l.activation
    - rect_fem_l.activation
    - vas_int_l.activation
    - gastroc_l.activation
    - soleus_l.activation
    - tib_ant_l.activation

# collector
collector:
  frames_per_batch: 128
  total_frames: 10_000_000
  learning_epochs: 5
  buffer_size: 128

# logger
logger:
  #backend: wandb
  exp_name: nair_walk_h0918_IL
  write_interval: 100_000
  test_interval: 100_000
  check_interval: 100_000
  num_test_episodes: 5

# Optim
optim:
  lr: 1e-3
  optimizer: KLAdaptiveRL
  optimizer_kwargs: {"kl_threshold": 0.008}
  weight_decay: 0.0
  anneal_lr: True

# loss
hiperparameters:
  clip_epsilon: 0.2
  entropy_coef: 0.9
  critic_coef: 1.0
  lmbda: 0.95
  gamma: 0.99 
  batch_size: 128
  mini_batch_size : 64
  max_grad_norm: 1.0
